### ISSUE TITLE
What versions does this support

### ISSUE THREAD

**Issue by CrankySupertoonArchive** [LexManos/LegacyJavaFixer#4]
I know it supports 1.6.4, 1.7.2 and the version up to the 1.7.10 version that fixed it. but does it support anything under 1.6.4, eg 1.5.2, **1.4.7**, 1.3.2, **1.2.5**, and the modloader + forge combos of 1.1, 1.0 , beta 1.8.1 and beta 1.7.3

**Comment by LexManos** [comment]
It *should* support all versions that use the cpw.mods named FML code. Which IIRC is 1.3+ As it's stupid old code. Feel free to comment on this issue with ones you've tested.

**Comment by phit** [comment]
is there a reason these are no longer on the forge maven?
https://files.minecraftforge.net/maven/net/minecraftforge/lex/legacyjavafixer/1.0/legacyjavafixer-1.0.jar
https://files.minecraftforge.net/LegacyJavaFixer/legacyjavafixer-1.0.jar
both of these links used to work, now a lot of support threads link to dead links because of this


working mirrors for people that need the releases:
https://dist.creeper.host/FTB2/maven/net/minecraftforge/lex/legacyjavafixer/1.0/legacyjavafixer-1.0.jar
https://ftb.forgecdn.net/FTB2/maven/net/minecraftforge/lex/legacyjavafixer/1.0/legacyjavafixer-1.0.jar

**Comment by LexManos** [comment]
I removed all old legacy redirects from the root of our file server as they are years old and people should of updated to the maven path by now.
As for where the maven artifact went... no idea... So reuploaded it.
